services:
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution_api
    restart: always
    env_file: .env
    ports:
      - '127.0.0.1:${SERVER_PORT}:8080'
    networks:
      - eddie3-networks
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_HOST=${REDIS_HOST}
      - CACHE_REDIS_PORT=${REDIS_PORT}
      - CACHE_REDIS_URI=redis://redis:${REDIS_PORT}
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
    volumes:
      - evolution_instances:/evolution/instances

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    restart: always
networks:
  eddie3-networks:
    external: true
volumes:
  evolution_instances:
  pg_data:
